spring:
  graphql:
    graphiql:
      enabled: true
  data:
    mongodb:
      # Connection string z parametrami poola
      uri: mongodb://localhost:27017/plants-library
      auto-index-creation: true  # tworzenie indeksów z adnotacji @Indexed

  # Twarde timeouty (przykładowe wartości)
  mongodb:
    socket-timeout: 5000   # ms
    connect-timeout: 3000  # ms

  lifecycle:
    timeout-per-shutdown-phase: 30s

server:
  shutdown: graceful
